FORMAT: 1A

# sample-service-api

RESTful JSON API-blueprint for registering and modifying all types of material (sample, library etc...).
It can create, read and update a material and add additional metadata to it.

## Material Type Collection [/material_types]

### List All Material Types [GET]

This action response with a list of all material types.

+ Response 200 (application/json)

        {
            "data": [
                {
                    "attributes": {
                        "name": "sample"
                    },
                    "id": "1",
                    "links": {
                        "self": "/api/v1/material_types/1"
                    },
                    "type": "material-types"
                },
                {
                    "attributes": {
                        "name": "library"
                    },
                    "id": "2",
                    "links": {
                        "self": "/api/v1/material_types/2"
                    },
                    "type": "material-types"
                }
            ]
        }

## Material Type [/material_types/{id}]
        
### Get a Material Type [GET]

This action response with the queried material type data.

+ Response 200 (application/json)

        {
            "data": {
                "attributes": {
                    "name": "sample"
                },
                "id": "1",
                "links": {
                    "self": "/api/v1/material_types/1"
                },
                "type": "material-types"
            }
        }

### Create a new Material Type [POST]

**THIS FEATURE IS NOT YET IMPLEMENTED!**

You can create a new Material Type using this action. It takes a JSON-API compatible
object containing data of the new Material Type.


+ Request (application/vnd.api+json)

        {
            "data": {
                "type": "material_types",
                "attributes": {
                    "name": "new material type"
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /material_types/3

    + Body

            {
                "data": {
                    "attributes": {
                        "name": "new material type"
                    },
                    "id": "3",
                    "links": {
                        "self": "/api/v1/material_types/3"
                    },
                    "type": "material-types"
                }
            }

## Material Collection [/materials]

### List All Materials [GET]

This action response with a list of all materials.

+ Response 200 (application/json)

        {
          "data": [
            {
              "id": "a53a07f0-ee83-0133-bcfa-685b35d4beab",
              "type": "materials",
              "attributes": {
                "name": "sample abc"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [

                  ]
                },
                "parents": {
                  "data": [

                  ]
                },
                "children": {
                  "data": [

                  ]
                }
              }
            },
            {
              "id": "a9186bb0-ee83-0133-bcfb-685b35d4beab",
              "type": "materials",
              "attributes": {
                "name": "sample def"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [

                  ]
                },
                "parents": {
                  "data": [

                  ]
                },
                "children": {
                  "data": [

                  ]
                }
              }
            }
          ],
          "included": [
            {
              "id": "1",
              "type": "material-types",
              "attributes": {
                "name": "sample"
              },
              "links": {
                "self": "/api/v1/material_types/1"
              }
            }
          ]
        }

## Material [/materials/{id}]

### Get a Material [GET]

This action response with the queried material data.

+ Response 200 (application/json)

       {
         "data": {
           "id": "75ed7330-ee86-0133-bcfd-685b35d4beab",
           "type": "materials",
           "attributes": {
             "name": "library 123"
           },
           "relationships": {
             "material-type": {
               "data": {
                 "id": "2",
                 "type": "material-types"
               }
             },
             "metadata": {
               "data": [
                 {
                   "id": "4",
                   "type": "metadata"
                 },
                 {
                   "id": "5",
                   "type": "metadata"
                 }
               ]
             },
             "parents": {
               "data": [
                 {
                   "id": "a53a07f0-ee83-0133-bcfa-685b35d4beab",
                   "type": "materials"
                 },
                 {
                   "id": "a9186bb0-ee83-0133-bcfb-685b35d4beab",
                   "type": "materials"
                 }
               ]
             },
             "children": {
               "data": [
                 {
                   "id": "109ec470-ee87-0133-bcff-685b35d4beab",
                   "type": "materials"
                 }
               ]
             }
           }
         },
         "included": [
           {
             "id": "2",
             "type": "material-types",
             "attributes": {
               "name": "library"
             },
             "links": {
               "self": "/api/v1/material_types/2"
             }
           },
           {
             "id": "4",
             "type": "metadata",
             "attributes": {
               "key": "gender",
               "value": "female"
             }
           },
           {
             "id": "5",
             "type": "metadata",
             "attributes": {
               "key": "taxon_id",
               "value": "9876"
             }
           }
         ]
       }

## Material creation and update [/materials/{id} POST]

You can create a new Material using this action. It takes a JSON-API compatible
object containing data of the new Material. It is mandatory to has a Material Type relationship.
It is optional to the material to has one or more metadata relationship(s).

### Create a new Material without attached metadata [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "name": "sample def"
                },
                "relationships": {
                    "material_type": {
                        "data": {
                            "attributes": {
                                "name": "sample"
                            }
                        }
                    }
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /materials/2

    + Body

        {
          "data": {
            "id": "a9186bb0-ee83-0133-bcfb-685b35d4beab",
            "type": "materials",
            "attributes": {
              "name": "sample def"
            },
            "relationships": {
              "material-type": {
                "data": {
                  "id": "1",
                  "type": "material-types"
                }
              },
              "metadata": {
                "data": [

                ]
              },
              "parents": {
                "data": [

                ]
              },
              "children": {
                "data": [

                ]
              }
            }
          },
          "included": [
            {
              "id": "1",
              "type": "material-types",
              "attributes": {
                "name": "sample"
              },
              "links": {
                "self": "/api/v1/material_types/1"
              }
            }
          ]
        }
            
### Create a new Material with attached metadata [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "name": "library 123"
                },
                "relationships": {
                    "material_type": {
                        "data": {
                            "attributes": {
                                "name": "library"
                            }
                        }
                    },
                    "metadata": {
                        "data": [
                            {
                                "attributes": {
                                    "key": "gender",
                                    "value": "female"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "taxon_id",
                                    "value": "5678"
                                }
                            }
                        ]
                    }
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /materials/37ad1d10-ee85-0133-bcfc-685b35d4beab

    + Body

        {
          "data": {
            "id": "37ad1d10-ee85-0133-bcfc-685b35d4beab",
            "type": "materials",
            "attributes": {
              "name": "library 123"
            },
            "relationships": {
              "material-type": {
                "data": {
                  "id": "2",
                  "type": "material-types"
                }
              },
              "metadata": {
                "data": [
                  {
                    "id": "2",
                    "type": "metadata"
                  },
                  {
                    "id": "3",
                    "type": "metadata"
                  }
                ]
              },
              "parents": {
                "data": [

                ]
              },
              "children": {
                "data": [

                ]
              }
            }
          },
          "included": [
            {
              "id": "2",
              "type": "material-types",
              "attributes": {
                "name": "library"
              },
              "links": {
                "self": "/api/v1/material_types/2"
              }
            },
            {
              "id": "2",
              "type": "metadata",
              "attributes": {
                "key": "gender",
                "value": "female"
              }
            },
            {
              "id": "3",
              "type": "metadata",
              "attributes": {
                "key": "taxon_id",
                "value": "5678"
              }
            }
          ]
        }

### Create a new Material with parent materials [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "name": "library 123"
                },
                "relationships": {
                    "material_type": {
                        "data": {
                            "attributes": {
                                "name": "library"
                            }
                        }
                    },
                    "parents": {
                        "data": [
                            {
                                "id": "a53a07f0-ee83-0133-bcfa-685b35d4beab"
                            },
                            {
                                "id": "a9186bb0-ee83-0133-bcfb-685b35d4beab"
                            }
                        ]
                    }
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /materials/75ed7330-ee86-0133-bcfd-685b35d4beab

    + Body

        {
          "data": {
            "id": "75ed7330-ee86-0133-bcfd-685b35d4beab",
            "type": "materials",
            "attributes": {
              "name": "library 123"
            },
            "relationships": {
              "material-type": {
                "data": {
                  "id": "2",
                  "type": "material-types"
                }
              },
              "metadata": {
                "data": [

                ]
              },
              "parents": {
                "data": [
                  {
                    "id": "a53a07f0-ee83-0133-bcfa-685b35d4beab",
                    "type": "materials"
                  },
                  {
                    "id": "a9186bb0-ee83-0133-bcfb-685b35d4beab",
                    "type": "materials"
                  }
                ]
              },
              "children": {
                "data": [

                ]
              }
            }
          },
          "included": [
            {
              "id": "2",
              "type": "material-types",
              "attributes": {
                "name": "library"
              },
              "links": {
                "self": "/api/v1/material_types/2"
              }
            }
          ]
        }
            
### Update an existing Material with modified name, material type and metadata [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "name": "sample 123"
                },
                "relationships": {
                    "material_type": {
                        "data": {
                            "attributes": {
                                "name": "sample"
                            }
                        }
                    },
                    "metadata": {
                        "data": [
                            {
                                "attributes": {
                                    "key": "gender",
                                    "value": "male"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "taxon_id",
                                    "value": "1234"
                                }
                            }
                        ]
                    }
                }
            }
        }

+ Response 200 (application/vnd.api+json)

    + Headers

            Location: /materials/37ad1d10-ee85-0133-bcfc-685b35d4beab

    + Body

            {
              "data": {
                "id": "37ad1d10-ee85-0133-bcfc-685b35d4beab",
                "type": "materials",
                "attributes": {
                  "name": "sample 123"
                },
                "relationships": {
                  "material-type": {
                    "data": {
                      "id": "1",
                      "type": "material-types"
                    }
                  },
                  "metadata": {
                    "data": [
                      {
                        "id": "2",
                        "type": "metadata"
                      },
                      {
                        "id": "3",
                        "type": "metadata"
                      }
                    ]
                  },
                  "parents": {
                    "data": [

                    ]
                  },
                  "children": {
                    "data": [

                    ]
                  }
                }
              },
              "included": [
                {
                  "id": "1",
                  "type": "material-types",
                  "attributes": {
                    "name": "sample"
                  },
                  "links": {
                    "self": "/api/v1/material_types/1"
                  }
                },
                {
                  "id": "2",
                  "type": "metadata",
                  "attributes": {
                    "key": "gender",
                    "value": "male"
                  }
                },
                {
                  "id": "3",
                  "type": "metadata",
                  "attributes": {
                    "key": "taxon_id",
                    "value": "1234"
                  }
                }
              ]
            }

## MaterialBatch Collection [/material_batches]

### List All MaterialBatches [GET]

This action response with a list of all material batches.

+ Response 200 (application/json)

        {        
          "data": [
            {
              "id": "1",
              "type": "material-batches",
              "attributes": {
                "name": "Material batch name 1"
              },
              "relationships": {
                "materials": {
                  "data": [
                    {
                      "id": "61088bd0-e905-0133-db54-005056bf12f5",
                      "type": "materials"
                    },
                    {
                      "id": "61096c50-e905-0133-db55-005056bf12f5",
                      "type": "materials"
                    },
                    {
                      "id": "610a4d10-e905-0133-db56-005056bf12f5",
                      "type": "materials"
                    }
                  ]
                }
              }
            }
          ],
          "included": [
            {
              "id": "61088bd0-e905-0133-db54-005056bf12f5",
              "type": "materials",
              "attributes": {
                "name": "material name 49"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [
                    {
                      "id": "3",
                      "type": "metadata"
                    },
                    {
                      "id": "4",
                      "type": "metadata"
                    },
                    {
                      "id": "5",
                      "type": "metadata"
                    }
                  ]
                }
              }
            },
            {
              "id": "1",
              "type": "material-types",
              "attributes": {
                "name": "sample"
              },
              "links": {
                "self": "/api/v1/material_types/1"
              }
            },
            {
              "id": "3",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 37",
                "value": "metadatum value 37"
              }
            },
            {
              "id": "4",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 38",
                "value": "metadatum value 38"
              }
            },
            {
              "id": "5",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 39",
                "value": "metadatum value 39"
              }
            },
            {
              "id": "61096c50-e905-0133-db55-005056bf12f5",
              "type": "materials",
              "attributes": {
                "name": "material name 53"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [
                    {
                      "id": "6",
                      "type": "metadata"
                    },
                    {
                      "id": "7",
                      "type": "metadata"
                    },
                    {
                      "id": "8",
                      "type": "metadata"
                    }
                  ]
                }
              }
            },
            {
              "id": "6",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 40",
                "value": "metadatum value 40"
              }
            },
            {
              "id": "7",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 41",
                "value": "metadatum value 41"
              }
            },
            {
              "id": "8",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 42",
                "value": "metadatum value 42"
              }
            },
            {
              "id": "610a4d10-e905-0133-db56-005056bf12f5",
              "type": "materials",
              "attributes": {
                "name": "material name 57"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [
                    {
                      "id": "9",
                      "type": "metadata"
                    },
                    {
                      "id": "10",
                      "type": "metadata"
                    },
                    {
                      "id": "11",
                      "type": "metadata"
                    }
                  ]
                }
              }
            },
            {
              "id": "9",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 43",
                "value": "metadatum value 43"
              }
            },
            {
              "id": "10",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 44",
                "value": "metadatum value 44"
              }
            },
            {
              "id": "11",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 45",
                "value": "metadatum value 45"
              }
            }
          ]
        }
        
## MaterialBatch [/material_batches/{id}]

### Get a Material Batch [GET]

This action response with the queried material batches data.

+ Response 200 (application/json)

        {
          "data": {
            "id": "1",
            "type": "material-batches",
            "attributes": {
              "name": "Material batch name 1"
            },
            "relationships": {
              "materials": {
                "data": [
                  {
                    "id": "61088bd0-e905-0133-db54-005056bf12f5",
                    "type": "materials"
                  },
                  {
                    "id": "61096c50-e905-0133-db55-005056bf12f5",
                    "type": "materials"
                  },
                  {
                    "id": "610a4d10-e905-0133-db56-005056bf12f5",
                    "type": "materials"
                  }
                ]
              }
            }
          },
          "included": [
            {
              "id": "61088bd0-e905-0133-db54-005056bf12f5",
              "type": "materials",
              "attributes": {
                "name": "material name 49"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [
                    {
                      "id": "3",
                      "type": "metadata"
                    },
                    {
                      "id": "4",
                      "type": "metadata"
                    },
                    {
                      "id": "5",
                      "type": "metadata"
                    }
                  ]
                }
              }
            },
            {
              "id": "1",
              "type": "material-types",
              "attributes": {
                "name": "sample"
              },
              "links": {
                "self": "/api/v1/material_types/1"
              }
            },
            {
              "id": "3",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 37",
                "value": "metadatum value 37"
              }
            },
            {
              "id": "4",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 38",
                "value": "metadatum value 38"
              }
            },
            {
              "id": "5",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 39",
                "value": "metadatum value 39"
              }
            },
            {
              "id": "61096c50-e905-0133-db55-005056bf12f5",
              "type": "materials",
              "attributes": {
                "name": "material name 53"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [
                    {
                      "id": "6",
                      "type": "metadata"
                    },
                    {
                      "id": "7",
                      "type": "metadata"
                    },
                    {
                      "id": "8",
                      "type": "metadata"
                    }
                  ]
                }
              }
            },
            {
              "id": "6",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 40",
                "value": "metadatum value 40"
              }
            },
            {
              "id": "7",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 41",
                "value": "metadatum value 41"
              }
            },
            {
              "id": "8",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 42",
                "value": "metadatum value 42"
              }
            },
            {
              "id": "610a4d10-e905-0133-db56-005056bf12f5",
              "type": "materials",
              "attributes": {
                "name": "material name 57"
              },
              "relationships": {
                "material-type": {
                  "data": {
                    "id": "1",
                    "type": "material-types"
                  }
                },
                "metadata": {
                  "data": [
                    {
                      "id": "9",
                      "type": "metadata"
                    },
                    {
                      "id": "10",
                      "type": "metadata"
                    },
                    {
                      "id": "11",
                      "type": "metadata"
                    }
                  ]
                }
              }
            },
            {
              "id": "9",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 43",
                "value": "metadatum value 43"
              }
            },
            {
              "id": "10",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 44",
                "value": "metadatum value 44"
              }
            },
            {
              "id": "11",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 45",
                "value": "metadatum value 45"
              }
            }
          ]
        }
        
## Material Batch creation and update [/material_batches/{id} POST]

You can create a new Material Batch using this action. It takes a JSON-API compatible
object containing data of the new Material Batch.
It is mandatory to has one or more Materials and the Materials has to be valid.

### Create a new Material Batch [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "name": "Material batch name 1"
                },
                "relationships": {
                    "materials": {
                        "data": [
                            {
                                "attributes": {
                                    "name": "material name 49"
                                },
                                "relationships": {
                                    "material_type": {
                                        "data": {
                                            "attributes": {
                                                "name": "sample"
                                            }
                                        }
                                    },
                                    "metadata": {
                                        "data": [
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 37",
                                                    "value": "metadatum value 37"
                                                }
                                            },
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 38",
                                                    "value": "metadatum value 38"
                                                }
                                            },
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 39",
                                                    "value": "metadatum value 39"
                                                }
                                            }
                                        ]
                                    }
                                }
                            },
                            {
                                "attributes": {
                                    "name": "material name 53"
                                },
                                "relationships": {
                                    "material_type": {
                                        "data": {
                                            "attributes": {
                                                "name": "sample"
                                            }
                                        }
                                    },
                                    "metadata": {
                                        "data": [
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 40",
                                                    "value": "metadatum value 40"
                                                }
                                            },
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 41",
                                                    "value": "metadatum value 41"
                                                }
                                            },
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 42",
                                                    "value": "metadatum value 42"
                                                }
                                            }
                                        ]
                                    }
                                }
                            },
                            {
                                "attributes": {
                                    "name": "material name 57"
                                },
                                "relationships": {
                                    "material_type": {
                                        "data": {
                                            "attributes": {
                                                "name": "sample"
                                            }
                                        }
                                    },
                                    "metadata": {
                                        "data": [
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 43",
                                                    "value": "metadatum value 43"
                                                }
                                            },
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 44",
                                                    "value": "metadatum value 44"
                                                }
                                            },
                                            {
                                                "attributes": {
                                                    "key": "metadatum key 45",
                                                    "value": "metadatum value 45"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /material_batches/1

    + Body

            {
                "data": {
                    "attributes": {
                        "name": "Material batch name 1"
                    },
                    "id": "1",
                    "relationships": {
                        "materials": {
                            "data": [
                                {
                                    "id": "61088bd0-e905-0133-db54-005056bf12f5",
                                    "type": "materials"
                                },
                                {
                                    "id": "61096c50-e905-0133-db55-005056bf12f5",
                                    "type": "materials"
                                },
                                {
                                    "id": "610a4d10-e905-0133-db56-005056bf12f5",
                                    "type": "materials"
                                }
                            ]
                        }
                    },
                    "type": "material-batches"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "material name 49",
                        },
                        "id": "61088bd0-e905-0133-db54-005056bf12f5",
                        "relationships": {
                            "material-type": {
                                "data": {
                                    "id": "1",
                                    "type": "material-types"
                                }
                            },
                            "metadata": {
                                "data": [
                                    {
                                        "id": "3",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "4",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "5",
                                        "type": "metadata"
                                    }
                                ]
                            }
                        },
                        "type": "materials"
                    },
                    {
                        "attributes": {
                            "name": "sample"
                        },
                        "id": "1",
                        "links": {
                            "self": "/api/v1/material_types/1"
                        },
                        "type": "material-types"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 37",
                            "value": "metadatum value 37"
                        },
                        "id": "3",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 38",
                            "value": "metadatum value 38"
                        },
                        "id": "4",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 39",
                            "value": "metadatum value 39"
                        },
                        "id": "5",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "name": "material name 53",
                        },
                        "id": "61096c50-e905-0133-db55-005056bf12f5",
                        "relationships": {
                            "material-type": {
                                "data": {
                                    "id": "1",
                                    "type": "material-types"
                                }
                            },
                            "metadata": {
                                "data": [
                                    {
                                        "id": "6",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "7",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "8",
                                        "type": "metadata"
                                    }
                                ]
                            }
                        },
                        "type": "materials"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 40",
                            "value": "metadatum value 40"
                        },
                        "id": "6",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 41",
                            "value": "metadatum value 41"
                        },
                        "id": "7",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 42",
                            "value": "metadatum value 42"
                        },
                        "id": "8",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "name": "material name 57",
                        },
                        "id": "610a4d10-e905-0133-db56-005056bf12f5",
                        "relationships": {
                            "material-type": {
                                "data": {
                                    "id": "1",
                                    "type": "material-types"
                                }
                            },
                            "metadata": {
                                "data": [
                                    {
                                        "id": "9",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "10",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "11",
                                        "type": "metadata"
                                    }
                                ]
                            }
                        },
                        "type": "materials"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 43",
                            "value": "metadatum value 43"
                        },
                        "id": "9",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 44",
                            "value": "metadatum value 44"
                        },
                        "id": "10",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 45",
                            "value": "metadatum value 45"
                        },
                        "id": "11",
                        "type": "metadata"
                    }
                ]
            }
            
### Update an existing Material Batch with modified name [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "name": "new name"
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /material_batches/1

    + Body

            {
                "data": {
                    "attributes": {
                        "name": "new name"
                    },
                    "id": "1",
                    "relationships": {
                        "materials": {
                            "data": [
                                {
                                    "id": "61088bd0-e905-0133-db54-005056bf12f5",
                                    "type": "materials"
                                },
                                {
                                    "id": "61096c50-e905-0133-db55-005056bf12f5",
                                    "type": "materials"
                                },
                                {
                                    "id": "610a4d10-e905-0133-db56-005056bf12f5",
                                    "type": "materials"
                                }
                            ]
                        }
                    },
                    "type": "material-batches"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "material name 49"
                        },
                        "id": "61088bd0-e905-0133-db54-005056bf12f5",
                        "relationships": {
                            "material-type": {
                                "data": {
                                    "id": "1",
                                    "type": "material-types"
                                }
                            },
                            "metadata": {
                                "data": [
                                    {
                                        "id": "3",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "4",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "5",
                                        "type": "metadata"
                                    }
                                ]
                            }
                        },
                        "type": "materials"
                    },
                    {
                        "attributes": {
                            "name": "sample"
                        },
                        "id": "1",
                        "links": {
                            "self": "/api/v1/material_types/1"
                        },
                        "type": "material-types"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 37",
                            "value": "metadatum value 37"
                        },
                        "id": "3",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 38",
                            "value": "metadatum value 38"
                        },
                        "id": "4",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 39",
                            "value": "metadatum value 39"
                        },
                        "id": "5",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "name": "material name 53",
                        },
                        "id": "61096c50-e905-0133-db55-005056bf12f5",
                        "relationships": {
                            "material-type": {
                                "data": {
                                    "id": "1",
                                    "type": "material-types"
                                }
                            },
                            "metadata": {
                                "data": [
                                    {
                                        "id": "6",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "7",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "8",
                                        "type": "metadata"
                                    }
                                ]
                            }
                        },
                        "type": "materials"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 40",
                            "value": "metadatum value 40"
                        },
                        "id": "6",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 41",
                            "value": "metadatum value 41"
                        },
                        "id": "7",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 42",
                            "value": "metadatum value 42"
                        },
                        "id": "8",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "name": "material name 57",
                        },
                        "id": "610a4d10-e905-0133-db56-005056bf12f5",
                        "relationships": {
                            "material-type": {
                                "data": {
                                    "id": "1",
                                    "type": "material-types"
                                }
                            },
                            "metadata": {
                                "data": [
                                    {
                                        "id": "9",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "10",
                                        "type": "metadata"
                                    },
                                    {
                                        "id": "11",
                                        "type": "metadata"
                                    }
                                ]
                            }
                        },
                        "type": "materials"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 43",
                            "value": "metadatum value 43"
                        },
                        "id": "9",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 44",
                            "value": "metadatum value 44"
                        },
                        "id": "10",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 45",
                            "value": "metadatum value 45"
                        },
                        "id": "11",
                        "type": "metadata"
                    }
                ]
            }
